#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

# install gdb
$XCLUSTER install_prog --dest=$tmp gdb

eval $($XCLUSTER env | grep -E '^KERNELDIR|__kver')
kdir=$KERNELDIR/$__kver

# install perf
f=$kdir/tools/perf/perf
test -x $f || die "Not executable [$f]"
$XCLUSTER install_prog --dest=$tmp $f

# install libbpf, bpftool, libxdp and local XDP progs
log "Building local XDP programs"
gittop=$(git rev-parse --show-toplevel)
for x in lib xdp-sctp; do
	log "  make $x"
	make -C $gittop/$x DEBUG=1 > /dev/null
	log "  make $x install"
	DESTDIR=$tmp make -C $gittop/$x install > /dev/null
done

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
