#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

# install libbpf, bpftool, libxdp and local XDP progs
gittop=$(git rev-parse --show-toplevel)
for x in lib xdp-sctp; do
	make -C $gittop/$x > /dev/null
	DESTDIR=$tmp make -C $gittop/$x install > /dev/null
done

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
