#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

# install gdbserver
f=gdbserver
log "Including $f"
$XCLUSTER install_prog --dest=$tmp $f

eval $($XCLUSTER env | grep -E '^KERNELDIR|__kver')
kdir=$KERNELDIR/$__kver

# install perf
f=$kdir/tools/perf/perf
test -x $f || die "Not executable [$f]"
log "Including $f"
$XCLUSTER install_prog --dest=$tmp $f

# # install selftests
# f=$kdir/tools/testing/selftests
# test -x $f/kselftest_install.sh || die "Not executable [$f]"
# log "Including $f"
# mkdir -p $tmp/selftests
# cd $f
# $f/kselftest_install.sh $tmp/selftests 2>&1 > /dev/null
# cd -

# install libbpf, bpftool, libxdp and local progs
log "Building local programs"
gittop=$(git rev-parse --show-toplevel)
for x in lib udp-client xdp-udp-reflector xdp-sctp; do
	test -z $EBPF_PLAYGROUND_CLEAN || log "  make $x clean"
	test -z $EBPF_PLAYGROUND_CLEAN || make -C $gittop/$x DEBUG=1 clean > /dev/null
	log "  make $x"
	make -C $gittop/$x DEBUG=1 > /dev/null
	log "  make $x install"
	DESTDIR=$tmp make -C $gittop/$x install > /dev/null
done

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
