name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo apt-get update
        sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu qemu-system-x86
        sudo usermod -a -G kvm,libvirt $USER

    - name: Get xcluster
      run: |
        mkdir ${{ runner.temp }}/xcluster
        wget -q -O ${{ runner.temp }}/xcluster.tar.xz https://github.com/Nordix/xcluster/releases/download/7.8.0/xcluster-7.8.0.tar.xz
        tar xvf ${{ runner.temp }}/xcluster.tar.xz -C ${{ runner.temp }}/
        ls -lrt ${{ runner.temp }}/xcluster/

    - name: Run tests
      run: |
        cd test/ovl/ebpf
        export XC_PATH=${{ runner.temp }}/xcluster
        . Envsettings
        ./ebpf.sh test start
