name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get xcluster
      run: |
        mkdir ${{ runner.temp }}/xcluster
        wget https://github.com/Nordix/xcluster/releases/download/7.8.0/xcluster-7.8.0.tar.xz -O ${{ runner.temp }}/xcluster.tar.xz
        tar xvf ${{ runner.temp }}/xcluster.tar.xz -C ${{ runner.temp }}/xcluster/
        find ${{ runner.temp }}

    - name: Run tests
      run: |
        cd test/ovl/ebpf
        . Envsettings
        ./ebpf.sh test start
