name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu qemu-kvm qemu-system-x86 xterm screen net-tools cpu-checker

    - name: Check env
      run: |
        lscpu
        kvm-ok

    - name: Get xcluster
      run: |
        mkdir ${{ runner.temp }}/xcluster
        wget -q -O ${{ runner.temp }}/xcluster.tar.xz https://github.com/Nordix/xcluster/releases/download/7.8.0/xcluster-7.8.0.tar.xz
        tar xvf ${{ runner.temp }}/xcluster.tar.xz -C ${{ runner.temp }}/
        ls -lrt ${{ runner.temp }}/xcluster/

    - name: Run tests
      run: |
        cd test/ovl/ebpf
        export XC_PATH=${{ runner.temp }}/xcluster
        . Envsettings
        ./ebpf.sh test start
