name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get xcluster
      run: |
        pwd
        wget https://github.com/Nordix/xcluster/releases/download/7.8.0/xcluster-7.8.0.tar.xz
        ls -lrt
        wget https://github.com/Nordix/xcluster/releases/download/7.8.0/xcluster-7.8.0.tar.xz -O /tmp/$USER/xcluster.tar.xz
        tar xvf /tmp/$USER/xcluster.tar.xz -C /tmp/$USER/xcluster/
        ls -lrt /tmp/$USER/

    - name: Run tests
      run: |
        cd test/ovl/ebpf
        . Envsettings
        ./ebpf.sh test start
